language: node_js
node_js: 
  - "stable"

install:
  - npm install

script:
  - npm run eslint
  - npm test --coverage
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  keep_history: true
  on:
    branch: master